version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/textDisplay
    overwrite: yes

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/initialize.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      runas: ubuntu