version: 0.2

phases:
  pre_build:
    commands:
      - cd textDisplay-frontend
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: textDisplay-frontend/build